### ISSUE TITLE
Incompatible CPU Architecture

### ISSUE THREAD

**Issue by AadiPatangi** [deltacv/EOCV-Sim#95] opened 2023-07-26 03:44 UTC
**Describe the bug**

*used by: java.lang.UnsatisfiedLinkError: /private/var/folders/20/f4mbvpk51v154ghfw4dcdplh0000gn/T/libapriltag.dylib: dlopen(/private/var/folders/20/f4mbvpk51v154ghfw4dcdplh0000gn/T/libapriltag.dylib, 0x0001): tried: '/private/var/folders/20/f4mbvpk51v154ghfw4dcdplh0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/20/f4mbvpk51v154ghfw4dcdplh0000gn/T/libapriltag.dylib' (no such file), '/private/var/folders/20/f4mbvpk51v154ghfw4dcdplh0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Gives me this error. I'm on a m2 mac

**Comment by c4glenn** [comment] 2023-07-26 03:49
related to #94

**Comment by serivesmejia** [comment] 2023-07-31 00:26
Hello !
I'll be tracking this in #94. This will be kept open until the issue is fixed

**Comment by serivesmejia** [comment] 2023-09-24 21:21
Fixed in [v3.5.1](https://github.com/deltacv/EOCV-Sim/releases/tag/v3.5.1)

**Closed by serivesmejia** 2023-09-24 21:21 UTC
Labels: bug
